services:
  nearby:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-production}
    # image: nearby-location-nearby:latest
    container_name: nearby
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-8080}
      - BASE_URL=http://localhost:${PORT:-8080}
      - MONGO_URL=mongodb://root:example@mongo:27017/nearby?authSource=admin
      - RESTART_POLICY=${RESTART_POLICY:-unless-stopped}
    # env_file:
    #   - .env
    depends_on:
      - mongo
    networks:
      - nearby-net
    restart: ${RESTART_POLICY:-unless-stopped}

  mongo:
    image: mongo:6.0
    container_name: nearby-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nearby
    volumes:
      - mongo-data:/data/db
    networks:
      - nearby-net

networks:
  nearby-net:
    name: nearby-net

volumes:
  mongo-data:
    name: mongo-data
